import '../globals.css';
import LogoutButton from '@/app/_components/logout-button';
import ProfilePage from '../utils/profile';
import { redirect } from 'next/navigation';
import { getCurrentSession } from '@/services/auth';
export const metadata = {
  title: 'EatWise',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const userSession = await getCurrentSession();

  if (!userSession) {
    redirect('/login');
  }

  return (
    <html lang="en">
      <body className="flex h-screen">
        <aside className="flex w-64 flex-col items-center gap-4 rounded-lg bg-gradient-to-b from-[#FAF8F4]/90 to-[#C7B590]/90 p-4 text-[#1C1C1C] shadow-xl backdrop-blur-sm">
          <div className="cardContent flex flex-col gap-4">
            <ProfilePage></ProfilePage>
          </div>

          <div className="cardContent flex flex-col gap-4">
            <a
              href="/create"
              className="rounded-md bg-[#DED2B3] px-5 py-2 text-center text-sm font-semibold text-[#1C1C1C] shadow-md transition duration-300 hover:bg-[#bda16d] active:scale-[0.98]"
            >
              Generate Meal Plan
            </a>
          </div>

          <div className="cardContent flex flex-col gap-4">
            <a
              href="#"
              className="rounded-md bg-[#DED2B3] px-5 py-2 text-center text-sm font-semibold text-[#1C1C1C] shadow-md transition duration-300 hover:bg-[#bda16d] active:scale-[0.98]"
            >
              Menu
            </a>
            <a
              href="/history"
              className="rounded-md bg-[#DED2B3] px-5 py-2 text-center text-sm font-semibold text-[#1C1C1C] shadow-md transition duration-300 hover:bg-[#bda16d] active:scale-[0.98]"
            >
              History
            </a>
            <a
              href="#"
              className="rounded-md bg-[#DED2B3] px-5 py-2 text-center text-sm font-semibold text-[#1C1C1C] shadow-md transition duration-300 hover:bg-[#bda16d] active:scale-[0.98]"
            >
              User Account
            </a>
          </div>

          <div className="cardContent mt-auto">
            <LogoutButton></LogoutButton>
          </div>
        </aside>

        <div className="relative flex-1 bg-white p-8">
          <div className="absolute top-4 right-6">
            <h1 className="text-2xl font-bold text-[#321E1E]">EatWise.</h1>
          </div>

          <main className="flex-1 bg-white p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
