import '../globals.css';

import Link from 'next/link';
import { redirect } from 'next/navigation';

import { getCurrentSession } from '@/services/auth';

import Sidebar from '@/app/common/sidebar';

export const metadata = {
  title: 'EatWise',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const userSession = await getCurrentSession();

  if (!userSession) {
    redirect('/login');
  }

  const additionalLinks = [
    {
      href: '/account',
      label: 'User Account',
    },
  ];

  return (
    <html lang="en">
      <body className="flex h-screen">

        <Sidebar additionalLinks={additionalLinks} />

        <div className="relative flex-1 bg-white p-8">
          <div className="absolute top-4 right-6">
            <h1 className="text-2xl font-bold text-[#321E1E]">EatWise.</h1>
          </div>

          <main className="flex-1 bg-white p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
