import '../globals.css';

import { Avatar } from '@radix-ui/react-avatar';
import { LogOut, LogOutIcon } from 'lucide-react';

import { Button } from '@/components/ui/button';
export const metadata = {
  title: 'EatWise',
  description: 'Generated by create next app',
};

// const user = {
//   name: session?.user?.name ?? 'Guest',
//   avatarUrl: session?.user?.image ?? null,
// };

// const getInitials = (name) =>
//   name
//     ?.split(' ')
//     .map((n) => n[0])
//     .join('')
//     .toUpperCase();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen">
        <aside className="flex w-64 flex-col items-center gap-4 rounded-lg bg-gradient-to-b from-[#FAF8F4]/90 to-[#C7B590]/90 p-4 text-[#1C1C1C] shadow-xl backdrop-blur-sm">
          <div className="cardContent flex flex-col items-center">
            {/* <Avatar.Root className="flex h-24 w-24 items-center justify-center overflow-hidden rounded-full bg-gray-300">
              <Avatar.Image className="h-full w-full object-cover" src={user.avatarUrl} alt={user.name} />
              <Avatar.Fallback delayMs={500} className="text-xl font-semibold text-white">
                {getInitials(user.name)}
              </Avatar.Fallback>
            </Avatar.Root> */}
            {/* <p className="mt-2 text-center text-sm text-white">{user.name}</p> */}
          </div>

          <div className="cardContent flex flex-col gap-4">
            <Button
              href="#"
              className="rounded-md bg-[#DED2B3] px-5 py-2 font-semibold text-[#1C1C1C] shadow-md transition duration-300 hover:bg-[#bda16d] active:scale-[0.98]"
            >
              Explore Menu
            </Button>
          </div>

          <div className="cardContent flex flex-col gap-4">
            <Button
              href="#"
              className="rounded-md bg-[#DED2B3] px-5 py-2 font-semibold text-[#1C1C1C] shadow-md transition duration-300 hover:bg-[#bda16d] active:scale-[0.98]"
            >
              Menu
            </Button>
            <Button
              href="#"
              className="rounded-md bg-[#DED2B3] px-5 py-2 font-semibold text-[#1C1C1C] shadow-md transition duration-300 hover:bg-[#bda16d] active:scale-[0.98]"
            >
              History
            </Button>
            <Button
              href="#"
              className="rounded-md bg-[#DED2B3] px-5 py-2 font-semibold text-[#1C1C1C] shadow-md transition duration-300 hover:bg-[#bda16d] active:scale-[0.98]"
            >
              User Account
            </Button>
          </div>

          <div className="cardContent mt-auto">
            <Button
              href="#"
              className="rounded-md bg-[#A58E7A] px-5 py-2 font-semibold text-[#FAF8F4] shadow-sm transition duration-300 hover:bg-[#8F7763] active:scale-[0.98]"
            >
              Logout
              <LogOut className="h-5 w-5" />
            </Button>
          </div>
        </aside>

        <div className="relative flex-1 bg-white p-8">
          <div className="absolute top-4 right-6">
            <h1 className="text-2xl font-bold text-[#321E1E]">EatWise.</h1>
          </div>

          <main className="flex-1 bg-white p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
