// 'use client'

// import { useEffect, useState } from 'react'

// import FoodModal from './foodModal'

// export default function WeeklyMenu() {
//   const [foods, setFoods] = useState([])
//   const [loading, setLoading] = useState(true)

//   useEffect(() => {
//     const fetchData = async () => {
//       const res = await fetch('/api/generate-foods')
//       const data = await res.json()
//       setFoods(data)
//       setLoading(false)
//     }

//     fetchData()
//   }, [])

//   return (
//     <div className="p-6">
//       <p className="mb-2 font-medium bg-yellow-100 px-2 py-1 w-fit rounded text-sm">
//         Week-1 (Generated by AI)
//       </p>

//       {loading ? (
//         <p className="text-gray-500">Loading menu...</p>
//       ) : (
//         <FoodModal foods={foods} />
//       )}
//     </div>
//   )
// }
